with source as(
    select *
    from {{ source('siape', 'siape_remuneracao') }}
),
final as(
    select
    {{ dbt_utils.star(from=source('siape', 'siape_remuneracao'), except=["remunera__o_b_sica_bruta_u", "abate_teto_u", "gratifica__o_natalina_u",
                                                                         "abate_teto_da_gratifica__o_natalina_u", "f_rias_u", "outras_remunera__es_eventuais_u",
                                                                         "irrf_u", "pssrpgs_u", "demais_dedu__es_u", "pens_o_militar_u", "fundo_de_sa_de_u",
                                                                         "taxa_de_ocupa__o_im_vel_funcional_u", "remunera__o_ap_s_dedu__es_obrigat_rias_u",
                                                                         "verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_civil_u",
                                                                         "verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_militar_u",
                                                                         "verbas_indenizat_rias_programa_desligamento_volunt_rio_mp_7922017_u",
                                                                         "total_de_verbas_indenizat_rias_u",
                                                                         "remunera__o_b_sica_bruta_r", "abate_teto_r", "gratifica__o_natalina_r",
                                                                         "abate_teto_da_gratifica__o_natalina_r", "f_rias_r", "outras_remunera__es_eventuais_r",
                                                                         "irrf_r", "pssrpgs_r", "demais_dedu__es_r", "pens_o_militar_r", "fundo_de_sa_de_r",
                                                                         "taxa_de_ocupa__o_im_vel_funcional_r", "remunera__o_ap_s_dedu__es_obrigat_rias_r",
                                                                         "verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_civil_r",
                                                                         "verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_militar_r",
                                                                         "verbas_indenizat_rias_programa_desligamento_volunt_rio_mp_7922017_r",
                                                                         "total_de_verbas_indenizat_rias_r"]) }},
    {{ converte_valor_bruto('remunera__o_b_sica_bruta_u') }} as remuneracao_basica_bruta_dolar,
    {{ converte_valor_bruto('abate_teto_u') }} as abate_teto_dolar,
    {{ converte_valor_bruto('gratifica__o_natalina_u') }} as gratificacao_natalina_dolar,
    {{ converte_valor_bruto('abate_teto_da_gratifica__o_natalina_u') }} as abate_teto_gratificacao_natalina_dolar,
    {{ converte_valor_bruto('f_rias_u') }} as ferias_dolar,
    {{ converte_valor_bruto('outras_remunera__es_eventuais_u') }} as outras_remuneracoes_eventuais_dolar,
    {{ converte_valor_bruto('irrf_u') }} as irrf_dolar,
    {{ converte_valor_bruto('pssrpgs_u') }} as pssrpgs_dolar,
    {{ converte_valor_bruto('demais_dedu__es_u') }} as demais_deducoes_dolar,
    {{ converte_valor_bruto('pens_o_militar_u') }} as pensao_militar_dolar,
    {{ converte_valor_bruto('fundo_de_sa_de_u') }} as fundo_saude_dolar,
    {{ converte_valor_bruto('taxa_de_ocupa__o_im_vel_funcional_u') }} as taxa_ocupacao_imovel_funcional_dolar,
    {{ converte_valor_bruto('remunera__o_ap_s_dedu__es_obrigat_rias_u') }} as remuneracao_deducoes_obrigatorias_dolar,
    {{ converte_valor_bruto('verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_civil_u') }} as verbas_indenizatorias_pessoal_civil_dolar,
    {{ converte_valor_bruto('verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_militar_u') }} as verbas_indenizatorias_pessoal_militar_dolar,
    {{ converte_valor_bruto('verbas_indenizat_rias_programa_desligamento_volunt_rio_mp_7922017_u') }} as verbas_indenizatorias_desligamento_voluntario_dolar,
    {{ converte_valor_bruto('total_de_verbas_indenizat_rias_u') }} as total_verbas_indenizatorias_dolar,
    {{ converte_valor_bruto('remunera__o_b_sica_bruta_r') }} as remuneracao_basica_bruta_reais,
    {{ converte_valor_bruto('abate_teto_r') }} as abate_teto_reais,
    {{ converte_valor_bruto('gratifica__o_natalina_r') }} as gratificacao_natalina_reais,
    {{ converte_valor_bruto('abate_teto_da_gratifica__o_natalina_r') }} as abate_teto_gratificacao_natalina_reais,
    {{ converte_valor_bruto('f_rias_r') }} as ferias_reais,
    {{ converte_valor_bruto('outras_remunera__es_eventuais_r') }} as outras_remuneracoes_eventuais_reais,
    {{ converte_valor_bruto('irrf_r') }} as irrf_reais,
    {{ converte_valor_bruto('pssrpgs_r') }} as pssrpgs_reais,
    {{ converte_valor_bruto('demais_dedu__es_r') }} as demais_deducoes_reais,
    {{ converte_valor_bruto('pens_o_militar_r') }} as pensao_militar_reais,
    {{ converte_valor_bruto('fundo_de_sa_de_r') }} as fundo_saude_reais,
    {{ converte_valor_bruto('taxa_de_ocupa__o_im_vel_funcional_r') }} as taxa_ocupacao_imovel_funcional_reais,
    {{ converte_valor_bruto('remunera__o_ap_s_dedu__es_obrigat_rias_r') }} as remuneracao_deducoes_obrigatorias_reais,
    {{ converte_valor_bruto('verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_civil_r') }} as verbas_indenizatorias_pessoal_civil_reais,
    {{ converte_valor_bruto('verbas_indenizat_rias_registradas_em_sistemas_de_pessoal_militar_r') }} as verbas_indenizatorias_pessoal_militar_reais,
    {{ converte_valor_bruto('verbas_indenizat_rias_programa_desligamento_volunt_rio_mp_7922017_r') }} as verbas_indenizatorias_desligamento_voluntario_reais,
    {{ converte_valor_bruto('total_de_verbas_indenizat_rias_r') }} as total_verbas_indenizatorias_reais
    from source
)
select * from final